app.version=0.1.0
app.cli.version=0.1.0
app.gui.version=0.0.0

module.clipboard.version=0.0.0
module.file_share.version=0.0.0
module.folder_sync.version=0.0.0
module.protocols.version=0.0.0
module.application_access.version=0.0.0
module.scheduler.version=0.0.0
module.host.version=0.0.0
module.client.version=0.0.0
module.mesh.version=0.0.0

logger.version=0.0.0

schema.version=0.1.0